export const GET_BRANCHES = 'GET_BRANCHES';
export const ADD_BRANCH = 'ADD_BRANCH';
export const DELETE_BRANCH = 'DELETE_BRANCH';
export const ADD_BRANCH_FAIL = 'ADD_BRANCH_FAIL';
export const ADD_BRANCH_SUCCESS = 'ADD_BRANCH_FAIL';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAIL = 'FORGOT_FAIL';
export const FORGOTRESET_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOTRESET_FAIL = 'FORGOT_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOADING_BASIC_SIM = 'LOADING_BASIC_SIM';
export const LOAD_BASIC_SIM_SUCCESS = 'LOAD_BASIC_SIM_SUCCESS';
export const LOAD_BASIC_SIM_FAIL = 'LOAD_BASIC_SIM_FAIL';

export const LOADING_SINGLE_SIM = 'LOADING_SINGLE_SIM';
export const LOAD_SINGLE_SIM_SUCCESS = 'LOAD_SINGLE_SIM_SUCCESS';
export const LOAD_SINGLE_SIM_FAIL = 'LOAD_SINGLE_SIM_FAIL';
